### ISSUE TITLE
[Question] About deepmerge & options

### ISSUE THREAD

**Issue by soulchainer** [guzart/neutrino-preset-airbnb#2]
Hi :D.

I saw you needed to commit to add again `deepmerge` to my PR (sorry >_<), and I want to ask, if you don't mind, what does this actually do/allow to do?

I don't fully get it, but it seems that it, enables some short of configuration of the preset (merging options)?

I ask this because, if is that what it does, then maybe I could change a local preset I have just for changing the ESLint config this preset extends. It changes the `envs` property of `eslint` this way:

```js
const eslint = require('neutrino-middleware-eslint');

module.exports = neutrino => {
  neutrino.use(eslint, {
    eslint: {
      baseConfig: { extends: ['airbnb'] },
      envs: ['browser', 'es6', 'node'],
    },
  });
};
```
If that custom options thing is what I think it's, I could be doing this another way, right?

Thanks for your time, @guzart.

**Comment by guzart** [comment]
Hi Juan,

I have to say that I am no expert in Neutrino, but AFAIK you could customize the eslint `env` property in two possible ways:

**[Simple](https://neutrino.js.org/customization/simple.html#module-rules)**

```js
// package.json
{
  "neutrino": {
    "config": {
      "module": {
        "rule": {
          "lint": {
            "loader": {
              "eslint": {
                "options": {
                  "envs": ["browser", "es6", "node"]
                }
              }
            }
          }
        }
      }
    }
  }
}
```

Uff!, I guess it's simple if you don't want to code and prefer a declarative style.

**[Advanced](https://neutrino.js.org/customization/advanced.html)**

```js
// assuming you've already define using airbnb preset in package.json
module.exports = neutrino => {
  neutrino.config.module
    .rule('lint')
    .use('eslint')
    .tap(options => Object.assign(options, { envs: ['browser', 'es6', 'node'] }));
};
```

**Getting to the properties**

The [neutrino-middleware-eslint](https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino-middleware-eslint/index.js#L10) assigns the eslint configuration properties in the "eslint" `Use` object under the "lint" `Rule` object, and there are two ways to get to them and modify them, via a package.json property (Simple), or programatically using custom middleware (Advanced).

Hope this helps you out.

**Comment by soulchainer** [comment]
Muchísimas gracias, @guzart :D // Thank you very much, @guzart :D.
I knew there should be a method to directly extend from this preset instead of having to import again eslint in my custom preset and all that. I went for the second way, of course, because is what I was already doing, like you saw in my initial comment.
Just applied this variation and still works grea and it's lets code, so... **It's great** :D.
I'm closing this, cleaning the issues tab.

Have a nice day, man 👍.

**Comment by guzart** [comment]
De nada, un placer haber podido ayudarte
